name: VS17-CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    name: windows-vs17
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {gen: Visual Studio 17 2022, arch: x64}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Configure
        working-directory: ${{github.workspace}}
        run: |
          vcpkg install utf8proc --triplet x64-windows
          vcpkg install pcre2 --triplet x64-windows
          vcpkg install shapelib --triplet x64-windows
          # vcpkg install libxml2 --triplet x64-windows
          cd vcpkg
          bootstrap-vcpkg.bat
          cd ..
          mkdir build
          cd build && cmake -G "${{matrix.gen}}" -A ${{matrix.arch}}  ..
      - name: Build
        working-directory: ${{github.workspace}}      
        run: cmake --build build
